name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debootstrap xorriso genisoimage binutils squashfs-tools grub-pc-bin grub-efi-amd64-bin dosfstools mtools xz-utils liblz4-tool zstd git curl rsync

    - name: Run build
      run: |
        echo "Starting build..."
        minios-live -
        echo "Build completed."
